- hosts: localhost
  roles:
  - role: sdkman
    sdkman_dir: /usr/local/sdkman
    sdkman_auto_answer: true
    sdkman_update: true
    sdkman_uninstall_packages:
    - { candidate: groovy, version: 1.8.9 }
    sdkman_install_packages:
    - { candidate: java, version: 8u131 }
    - { candidate: gradle, version: '3.5' }
    - { candidate: gradle, version: 2.14.1 }
    - { candidate: maven, version: 3.5.0 }
    - { candidate: maven, version: 3.3.9 }
    sdkman_defaults:
      java: 8u131
      gradle: '3.5'
      maven: 3.3.9
